name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Deploy

    steps:
      - uses: actions/checkout@master

      - name: Publish regular files
        uses: nogsantos/scp-deploy@master
        with:
          src: ./www/*
          host: ${{ secrets.STRATO_SSH_HOST }}
          remote: rueckenschwimmer
          port: 22
          user: ${{ secrets.STRATO_SSH_USER }}
          key: ${{ secrets.STRATO_SSH_KEY }}

      - name: Publish hidden file .htaccess
        uses: nogsantos/scp-deploy@master
        with:
          src: ./www/.htaccess
          host: ${{ secrets.STRATO_SSH_HOST }}
          remote: rueckenschwimmer
          port: 22
          user: ${{ secrets.STRATO_SSH_USER }}
          key: ${{ secrets.STRATO_SSH_KEY }}
